services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      #DATABASE_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-api-platform}:${MONGO_INITDB_ROOT_PASSWORD:-test}@database:27017/${MONGO_INITDB_DATABASE:-api}?authSource=admin
      MONGODB_URL: mongodb://mongodb:27017
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-90}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-444}
        protocol: tcp
      # HTTP/3
      # - target: 443
      #   published: ${HTTP3_PORT:-443}
      #   protocol: udp

  pwa:
    image: ${IMAGES_PREFIX:-}app-pwa
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://php

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: api
      MONGO_INITDB_ROOT_USERNAME: api-platform
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - db_data:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  caddy_data:
  caddy_config:
  db_data:
